spin_version = "1"
authors = ["David Flanagan <david@rawkode.dev>"]
description = ""
name = "challenge-one-rust"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "challenge-one-rust"
source = "target/wasm32-wasi/release/challenge_one_rust.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
